export const GET_STAGEPROCEESING_REQUEST = "GET_STAGEPROCEESING_REQUEST";
export const GET_STAGEPROCEESING_SUCCESS = "GET_STAGEPROCEESING_SUCCESS";
export const GET_STAGEPROCEESING_ERROR = "GET_STAGEPROCEESING_ERROR";
export const RESET_STAGEPROCESSING="RESET_STAGEPROCESSING";
export const GET_ERRORPROCESSING_REQUEST = "GET_ERRORPROCESSING_REQUEST";
export const GET_ERRORPROCESSING_SUCCESS = "GET_ERRORPROCESSING_SUCCESS";
export const GET_ERRORPROCESSING_ERROR = "GET_ERRORPROCESSING_ERROR";
export const POST_ERRORPROCESSING_REQUEST = "POST_ERRORPROCESSING_REQUEST";
export const POST_ERRORPROCESSING_SUCCESS = "POST_ERRORPROCESSING_SUCCESS";
export const POST_ERRORPROCESSING_ERROR = "POST_ERRORPROCESSING_ERROR";
export const GET_CLASSDATA_REQUEST = "GET_CLASSDATA_REQUEST";
export const GET_CLASSDATA_SUCCESS = "GET_CLASSDATA_SUCCESS";
export const GET_CLASSDATA_ERROR = "GET_CLASSDATA_ERROR";
export const GET_LOCATIONDATA_REQUEST = "GET_LOCATIONDATA_REQUEST";
export const GET_LOCATIONDATA_SUCCESS = "GET_LOCATIONDATA_SUCCESS";
export const GET_LOCATIONDATA_ERROR = "GET_LOCATIONDATA_ERROR";
export const GET_SYSTEMCONFIG_REQUEST = "GET_SYSTEMCONFIG_REQUEST";
export const GET_SYSTEMCONFIG_SUCCESS = "GET_SYSTEMCONFIG_SUCCESS";
export const GET_SYSTEMCONFIG_ERROR = "GET_SYSTEMCONFIG_ERROR";
export const POST_SYSTEMCONFIG_REQUEST = "POST_SYSTEMCONFIG_REQUEST";
export const POST_SYSTEMCONFIG_SUCCESS = "POST_SYSTEMCONFIG_SUCCESS";
export const POST_SYSTEMCONFIG_ERROR = "POST_SYSTEMCONFIG_ERROR";
export const GET_GLACCOUNT_REQUEST = "GET_GLACCOUNT_REQUEST";
export const GET_GLACCOUNT_SUCCESS = "GET_GLACCOUNT_SUCCESS";
export const GET_GLACCOUNT_ERROR = "GET_GLACCOUNT_ERROR";
export const POST_GLACCOUNT_REQUEST = "POST_GLACCOUNT_REQUEST";
export const POST_GLACCOUNT_SUCCESS = "POST_GLACCOUNT_SUCCESS";
export const POST_GLACCOUNT_ERROR = "POST_GLACCOUNT_ERROR";
export const GET_GLACCOUNTCREATION_REQUEST = "GET_GLACCOUNTCREATION_REQUEST";
export const GET_GLACCOUNTCREATION_SUCCESS = "GET_GLACCOUNTCREATION_SUCCESS";
export const GET_GLACCOUNTCREATION_ERROR = "GET_GLACCOUNT_ERROR";
export const POST_GLACCOUNTCREATION_REQUEST = "POST_GLACCOUNTCREATION_REQUEST";
export const POST_GLACCOUNTCREATION_SUCCESS = "POST_GLACCOUNTCREATION_SUCCESS";
export const POST_GLACCOUNTCREATION_ERROR = "POST_GLACCOUNTCREATION_ERROR";
export const GET_GLCURRENCY_REQUEST = "GET_GLCURRENCY_REQUEST";
export const GET_GLCURRENCY_SUCCESS="GET_GLCURRENCY_SUCCESS";
export const GET_GLCURRENCY_ERROR="GET_GLCURRENCY_ERROR";
export const POST_GLCREATION_REQUEST = "POST_GLCREATION_REQUEST";
export const POST_GLCREATION_SUCCESS = "POST_GLCREATION_SUCCESS";
export const POST_GLCREATION_ERROR = "POST_GLCREATION_ERROR";




